django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    #connect path to portfolio_app urls
    path('', include('parent_resource_app.urls')),
    path('rosetta/', include('rosetta.urls')), #translation page - can go to to write translations
)

parent_resource_app/urls.py
from django.urls import path, include
from . import views



urlpatterns = [
#path function defines a url pattern
#'' is empty to represent based path to app
# views.index is the function defined in views.py
# name='index' parameter is to dynamically create url
# example in html <a href="{% url 'index' %}">Home</a>.
    path('', views.index, name='index'),
    path('groups/', views.OrganizationListView.as_view(), name='organizations'),
    path('groups/<int:pk>', views.OrganizationDetailView.as_view(), name='organization-detail'),
    path('events/<int:pk>/', views.EventDetailView.as_view(), name='event-detail'),
    path('group/<int:organization_id>/createEvent', views.createEvent, name='createEvent'),
    path('group/<int:organization_id>/updateEvent/<int:event_id>', views.updateEvent, name='updateEvent'),
    path('group/<int:organization_id>/deleteEvent/<int:event_id>', views.deleteEvent, name='deleteEvent'),
    path('group/<int:organization_id>/updateGroup', views.updateOrganization, name='updateOrganization'),

    #user accounts
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', views.registerPage, name = 'register-page'),
    path('accounts/logout', views.logoutView, name='logout'),
    path('user/', views.userPage, name='user_page'),


    #translation
    path('i18n/', include('django.conf.urls.i18n')),
    

]

parent_resource_app/models.py
from django.db import models
from django.urls import reverse
from multiselectfield import MultiSelectField
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

 

# Create your models here.


#HAD TO CHANGE FROM "GROUP" to "ORGANIZATION" BECAUSE OF CONFLICT WITH DJANGO AUTH GROUP 
class Organization(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)    

    name = models.CharField(_('Name'), max_length=200)
    email = models.EmailField(_('Email'), max_length=200)
    phone = models.CharField(_('Phone'), max_length= 20, null=True)
    about = models.TextField(_('about'), max_length=200)
    #@receiver(post_save, sender=User)
    #def create_user_organization(sender, instance, created, **kwargs):
    #    if created:
    #   Organization.objects.create(user=instance)

    #@receiver(post_save, sender=User)
    #def save_user_organization(sender, instance, **kwargs):
    # print("save",sender, instance,**kwargs)
    #instance.organization.save()

    #Define default String to return the name for representing the Model object."
    def __str__(self):
        return self.name

    #Returns the URL to access a particular instance of MyModelName.
    #if you define this method then Django will automatically
    # add a "View on Site" button to the model's record editing screens in the Admin site
    def get_absolute_url(self):
        return reverse('organization-detail', args=[str(self.id)])



class Event(models.Model):
    #List of choices for major value in database, human readable name
    SERVICES = (
    ('Family Fun', _('Family Fun')),  
    ('Health and Well-being', _('Health and Well-being')),
    ('Benefits or Financial Aid', _('Benefits or Financial Aid')),
    )

    #The left must include text value, not just number
    AGEGROUP = (
        ('0y', _('0-1 years')),
        ('1y', _('1-2 years')),
        ('2y', _('2-3 years')),
        ('3y', _('3-4 years')),
        ('4y', _('4-5 years')),
        ('5y', _('5-6 years')),
        ('6y', _('6-7 years')),
        ('7y', _('7-8 years')),
        ('8y', _('8-9 years')),
        ('9y', _('9-10 years')),
        ('10y', _('10-11 years')),
        ('11y', _('11-12 years')),
        ('12y', _('12-13 year')),
        ('13+', _('13 or older')),
        ('P', _('For Parents')),
        ('All', _('All ages')),
    )

 
    title = models.CharField(_('Title'), max_length=200)
    service_type = models.CharField(_("Type of Event"), max_length=200, choices=SERVICES)
    price = models.DecimalField(_('Price'), max_digits=5, decimal_places=2)
    age_group = MultiSelectField(_('Age Group'), choices=AGEGROUP, max_length=25)
    description = models.TextField(_('Description'), max_length=200)
    location = models.CharField(_('Location'), max_length=200, null = True, blank=True)
    start_date = models.DateField(_('Start Date'), auto_now=False, auto_now_add=False, null=True, blank=True)
    end_date = models.DateField(_('End Date'), auto_now=False, auto_now_add=False, null=True, blank=True)
    
    
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, default=None)


    #Define default String to return the name for representing the Model object."
    def __str__(self):
        return self.title

    #Returns the URL to access a particular instance of MyModelName.
    #if you define this method then Django will automatically
    # add a "View on Site" button to the model's record editing screens in the Admin site
    def get_absolute_url(self):
        return reverse('event-detail', args=[str(self.id)])

parent_resource_app/forms.py
from django.forms import ModelForm
from .models import Event, Organization
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


#create class for project form
class EventForm(ModelForm):
    class Meta:
        model = Event
        fields ='__all__'
        exclude = ['organization']

        #Widgets are used to format the form we'll sent to the HTML template. In this case, we're
        #using bootstraps form templates
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'service_type': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'age_group': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'start_date': forms.DateInput(attrs={'class': 'form-group', 'placeholder': 'YYYY-MM-DD'}),
            'end_date': forms.DateInput(attrs={'class':'form-group', 'placeholder': 'YYYY-MM-DD'}),
        }
    

class OrganizationForm(ModelForm):
    class Meta:
        model = Organization
        fields ='__all__'
        exclude = ['user']

        #Widgets are used to format the form we'll sent to the HTML template. In this case, we're
        #using bootstraps form templates
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'NO PROFILE INFO, PLEASE UPDATE'}), #class is a bootstrap class
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'about': forms.Textarea(attrs={'class': 'form-control'}),
        }



#start_date = forms.DateField(
 #   widget=forms.DateInput(
  #      attrs={
   #         'class' : 'form-control',
    #        'type' : "date"
     #   }
    #),
   # initial='04-01-2024'

#)        

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields =['username', 'email', 'password1', 'password2']



        

parent_resource_app/views.py
from django.shortcuts import *
from django.http import HttpResponse
from .models import *
from django.views import generic
from django.utils import timezone
from django.db.models import Q
from .forms import *
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .decorators import allowed_users, user_is_owner
from django.utils.translation import gettext as _




# Create your views here.



def index(request):
    #I got help from Chat GPT on this querey
    # Get current date and time
    current_date = timezone.now()

    # Filter events with end dates in the future __gt is django sytanx for greater than
    #Q is a django object that let's you make complex quieries by combining multiple conditions
    future_events = Event.objects.filter(Q(end_date__gt=current_date) | Q(end_date__isnull=True))

    # Pass the filtered events to the template
    return render(request, 'parent_resource_app/index.html', {'future_events': future_events})



def logoutView(request):
    logout(request)
    return render(request, 'registration/logout_complete.html')

@login_required(login_url='login')
@allowed_users(allowed_roles=['organization_role'])
@user_is_owner()
def createEvent(request, organization_id):
   form = EventForm()
   organization = Organization.objects.get(pk=organization_id)

   if request.method == 'POST':
      #Create a new dictionary with form data and organization_id
      event_data = request.POST.copy()
      event_data['organization_id'] = organization_id
      form = EventForm(event_data)
      if form.is_valid():
         start_date = form.cleaned_data['start_date']
         #Save the form without committing to the database
         event = form.save(commit=False)
         #Set the group relationship
         event.organization = organization
         event.save()

         #redirect back to the group detail page
         return redirect('organization-detail', organization_id)
   else:
      form = EventForm()


   context = {'form': form }
   return render( request, 'parent_resource_app/event_form.html', context )
   

@login_required(login_url='login')
@allowed_users(allowed_roles=['organization_role'])
@user_is_owner()
def updateEvent(request, organization_id, event_id):
   event = get_object_or_404(Event, pk=event_id)
   organization = event.organization

   if request.method == 'POST':
      #Create a new dictionary with form data and group_id
      event_data = request.POST.copy()
      event_data['organization_id'] = organization_id
      form = EventForm(request.POST, instance=event)
      if form.is_valid():
         #Save the form without committing to the database
         event = form.save(commit=False)
         #Set the group relationship
         event.organization = organization
         event.save()

         #redirect back to the group detail page
         return redirect('organization-detail', organization_id)
   else:
      form = EventForm(instance=event)

   context = {'form': form, 'event': event}
   return render(request, 'parent_resource_app/update_event.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['organization_role'])
@user_is_owner()
def deleteEvent(request, organization_id, event_id):
   event = get_object_or_404(Event, pk=event_id)
    
   
   if request.method == 'POST':
      # Confirming the delete request
      event.delete()
      # Redirect back to the group detail page
      return redirect('organization-detail', organization_id)

    # If the request method is not POST (e.g., GET), render the confirmation template
   context = {'event': event}
   return render(request, 'parent_resource_app/delete_event.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['organization_role'])
@user_is_owner()
def updateOrganization(request, organization_id):
   organization = get_object_or_404(Organization, pk=organization_id)
   
   if request.method == 'POST':
      #Create a new dictionary with form data and group_id
      organization_data = request.POST.copy()
      organization_data['organization_id'] = organization_id
      form = OrganizationForm(request.POST, instance=organization)
      if form.is_valid():
         #Save the form without committing to the database
         organization = form.save(commit=False)
         #Set the group relationship
         organization.organization = organization
         organization.save()

         #redirect back to the group detail page
         return redirect('organization-detail', organization_id)
   else:
      form = OrganizationForm(instance=organization)

   context = {'form': form, 'organization': organization}
   return render(request, 'parent_resource_app/update_organization.html', context)



def registerPage(request):
   form = CreateUserForm()

   if request.method =='POST':
      form = CreateUserForm(request.POST)
      if form.is_valid():
         user = form.save()
         username = form.cleaned_data.get('username')
         group = Group.objects.get(name='organization_role')
         user.groups.add(group)
         organization = Organization.objects.create(user=user,)
         organization.save()

         messages.success(request, 'Account was created for ' + username)
         return redirect('login')
      
   context = {'form': form}
   return render(request, 'registration/register.html', context)

 


@login_required(login_url='login')
@allowed_users(allowed_roles=['organization_role'])
@user_is_owner()
def userPage(request):
   organization = request.user.organization
   events = Event.objects.filter(organization_id=organization.id)
   form = OrganizationForm(instance = organization)
   print('organization', organization)
   if request.method == 'POST':
      form = OrganizationForm(request.POST, request.FILES, instance=organization)
      if form.is_vaild():
         form.save()
   context = {'organization': organization, 'form':form}
   return render(request, 'parent_resource_app/user.html', context)




class OrganizationListView(generic.ListView):
   model = Organization

class OrganizationDetailView(generic.DetailView):
   model = Organization

   
class EventListView(generic.ListView):
   model = Event

class EventDetailView(generic.DetailView):
   model = Event

parent_resource_app/templates/parent_resource_app/base_template.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load i18n %}
    <title>Parent Resources</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">



    <style>
      h1{
        padding-left: 7px;
        font-weight: bold;
      }


      h3{
        color: white;
      }
      .normal
      {
        padding-left:0;
      }
      
      .detail{
        padding-left:10px;
      }
  
     .list-group{
        padding-left: 10px;
     }
     
     .card-header{
        font-weight: bold;
        font-size: 30px;
        color: white;
        background-color: #080808;
        padding-bottom: 0px;
     }
     .card{
      color: white;
      margin-left: 10px;
      margin-bottom: 40px; 
      background-color:  #080808;
      border-weight: 0px;
      }
  
      .a{
        list-style: none;
        padding:10px;
        padding-left: 20px;
        background-color:  #080808;
        color: white;
  
      }
  
 
      .edit_button, .button{
        font-weight: 650;
        background-color: #lightgrey;
        color: black;
        border-radius: 10px;
        border-width: 4px;
        margin-left:10px;
        width: 180px;
        height: 40px;
       
        
      }  
  
      .form{
        margin-left = 10px;
        border-radius: 10px;
  
      }
      body{
        background-color: #292929;
        color: white;
      }
  
  
  
      ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #898197;
      }
      
      li {
        float: left;
      }


      .d-grid{
        margin-left: 7px;
        color: white;
        border-radius: 10px;
      }


      nav, li a, .dropbtn{
        color: black;
        font-weight: bold;
        background-color: #898197;
        display: inline-block;
        text-align: left;
        padding: 14px 16px;
        text-decoration: none;
      }
      
      li a:hover, .dropdown:hover .dropbtn {
        background-color: white;
      }
      
      
      .dropdown-content {
        display: none;
        position: absolute;
        background-color: white;
        color: black;
        font-weight: bold;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 100;
        position: fixed;
      }
      
      
      .dropdown-content a:hover {background-color: #f1f1f1;}
      
      .dropdown:hover .dropdown-content {
        display: block;
      }
    
    </style>



</head>

<body>
    <!-- Navbar-->
    <nav class="navbar navbar-expand">
        <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'images/colorado_logo.png' %}" style="width: 225px; height: 100px;"></a>
        <div class="container-fluid">
            <ul>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'index' %}">{% translate "HOME" %}</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'organizations' %}">{% translate "GROUPS" %}</a></li>
                <li class="dropdown">
                    <a href="javascript:void(0)" class="dropbtn">{% translate "ACCOUNT" %}</a>
                    <div class="dropdown-content">
                        {% if user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'user_page' %}">{% translate "PROFILE" %}</a>
                            <a class="dropdown-item" href="{% url 'logout' %}">{% translate "LOGOUT" %}</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'login' %}">{% translate "LOGIN" %}</a>
                            <a class="dropdown-item" href="{% url 'register-page' %}">{% translate "REGISTER" %}</a>
                        {% endif %}
                    </div>
                </li>

                <li class="dropdown">
                    <a href="javascript:void(0)" class="dropbtn">{% translate "LANGUAGE" %}</a>
                    <div class="dropdown-content">
                        <a class="dropdown-item" href="/en/">{% translate "English" %}</a>
                        <a class="dropdown-item" href="/es/">{% translate "Spanish" %}</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <br>

    <div class="container-fluid">
        <div class="col-sm-10">
            <!-- add block content from html template -->
            {% block content %}

            {% endblock %}
        </div>
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
</body>
</html>


  

parent_resource_app/templates/parent_resource_app/create_organization.html
{% extends 'parent_resource_app/base_template.html' %}
{% load i18n %}

{% block content %}

    <h1>{% trans "Create Your Group's Profile" %}</h1>
    <form action="" method="POST">

        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        
        <input class="button" type="submit" name="Submit">

    </form>

{% endblock %}

parent_resource_app/templates/parent_resource_app/delete_event.html
{% extends 'parent_resource_app/base_template.html' %}

{% block content%}

<p>_(Are you sure you want to delete?){{ event.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button class="button" type="submit">_(Confirm Delete)</button>
        <a href="{% url 'organization-detail' event.organization_id %}"><button class="button">_(Cancel)</button></a>
    </form>
    
{%endblock%} 

parent_resource_app/templates/parent_resource_app/event_detail.html
{% extends 'parent_resource_app/base_template.html' %}
{% load i18n %}

{% block content%}
    <div class="card">
        <p class="card-header">{{ event.title }}</p>
        <div class="card-body">
            <p class="card-text"><strong>{% translate "Event Type:" %} </strong>{{event.service_type}}</p>
            <p class="card-text"><strong>{% translate "Price:" %} </strong>{{event.price}}</p>
            <p class="card-text"><strong>{% translate "Description:" %} </strong>{{event.description}}</p>
            <p class="card-text"><strong>{% translate "For Ages:" %} </strong>{{event.age_group}}</p>
            <p class="card-text"><strong>{% translate "Where:" %} </strong>{{event.location}}</p>
            <p class="card-text"><strong>{% translate "When:" %} </strong> {{ event.start_date|date:"M d" }} - {{ event.end_date|date:"M d" }}</p>
        </div>
    </div>
    
    <p>
        {% if user.id == event.organization.user.id %}
            <a aria-current="page" href="{% url 'updateEvent' event.organization.id event.id %}" ><button class="edit_button">{% translate "Edit" %}</button></a>
            <a aria-current="page" href="{% url 'deleteEvent' event.organization.id event.id %}"><button class="edit_button">{% translate "Delete" %}</button></a> 
        {% endif %}
    </p>
{% endblock %}

parent_resource_app/templates/parent_resource_app/event_form.html
{% extends 'parent_resource_app/base_template.html' %}

{% block content%}
    
    <form action="" method="POST">

            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            
            <input class="button" type="submit" name="Submit">

    </form>
{% endblock %}

parent_resource_app/templates/parent_resource_app/group_detail.html
{% extends 'parent_resource_app/base_template.html' %}

{% block content%}

    <h1>{{ group.name }}</h1><p><a aria-current="page" href="{% url 'updateGroup' group.id %}"><button class="button">Edit Group Info</button></a></p> <br><br>
    <p class="detail"><strong>Email:</strong> {{group.email}}</p>
    <p class="detail"><strong>About:</strong><br> {{group.about}}</p>
    <h2><strong>Events:</strong></h2> <a aria-current="page" href="{% url 'createEvent' group.id %}"><button class="button">Create New Event</button></a>
    <br><br>

    
    {% if group.event_set.all %}
        <ul>
           {% for event in group.event_set.all %}
              <li class="a"><a class="textlink" href="{{ event.get_absolute_url }}" >{{ event.title }}</a><br><br>
              {{event.description}}  <br><br>
              <a aria-current="page" href="{% url 'updateEvent' group.id event.id %}" ><button class="edit_button">Edit</button></a>
              <a aria-current="page" href="{% url 'deleteEvent' group.id event.id %}"><button class="edit_button">Delete</button></a> 
            </li><br>
           {% endfor %}
        </ul>
    {% else %}
        <p>There are no events from this group.</p>
    {% endif %}
       

{% endblock %}

parent_resource_app/templates/parent_resource_app/group_list.html
{% extends 'parent_resource_app/base_template.html' %}

{% block content %}
    <h1>Groups in Colorado</h1><br>
    {% if group_list %}
        <ul class="list-group">
            {% for group in group_list %}
                <li class="a"><h2 class="normal">{{ group.name }}</h2>
                    <p><strong>About: </strong>{{group.about}}</p>
                    <a href="{{ group.get_absolute_url }}"><button class="edit_button">View Details</button></a>
                </li> <br>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no groups registered.</p>
    {% endif %}
{% endblock %}

parent_resource_app/templates/parent_resource_app/index.html
{% extends "parent_resource_app/base_template.html" %}
{% load i18n %}
{% block content %}
<h1>{% trans "Upcoming Events" %}</h1><br>
{% if future_events %}
    <div class="d-grid">
        {% for event in future_events %}
            <div class="a">
                <h2>{{ event.title }} </h2><br> 
                <p>{{ event.description }}</p>
                <p>{% trans "Ages" %}: {{ event.age_group }}</p>
                <p>{{ event.start_date|date:"M d" }} - {{ event.end_date|date:"M d" }}</p>
                <p>{% trans "Offered by" %}: {{ event.organization.name }}</p>
                <a href="{{ event.get_absolute_url }}" ><button class="edit_button">{% trans "Event Details" %}</button></a>
                <a href="{{ event.organization.get_absolute_url }}" ><button class="edit_button">{% trans "Group Details" %}</button></a>
            </div><br><br>
        {% endfor %}
        </div>

    {% else %}
        <p>{% trans "There are no upcoming events registered." %}</p>
    {% endif %}

{% endblock %}

parent_resource_app/templates/parent_resource_app/organization_detail.html
{% extends 'parent_resource_app/base_template.html' %}
{% load i18n %}

{% block content %}
    
    <br>
    <div class="card">
        <p class="card-header">{{ organization.name }} </p>
        <div class="card-body">
            <p class='card-text'><strong>{% trans "Email" %}:</strong> {{ organization.email }}</p>
            <p class='card-text'><strong>{% trans "Phone" %}:</strong> {{ organization.phone }}</p>
            <p class='card-text'> {% trans organization.about %}</p>
        </div>
    </div>

    {% if user.id == organization.user.id  %}
        <a aria-current="page" href="{% url 'updateOrganization' organization.id %}"><button class="button">{% trans "Edit Profile" %}</button></a>
        <a aria-current="page" href="{% url 'createEvent' organization.id %}"><button class="button">{% trans "Create New Event" %}</button></a> <br><br>
    {% endif %}

    {% if organization.event_set.all %}
        <div class="d-grid">
            {% for event in organization.event_set.all %}
                <div class="a">
                    <h3><a href="{{ event.get_absolute_url }}">{{ event.title }}</a></h3>
                    <p>{{ event.description }}</p>
                    {% if user.id == organization.user.id%}
                        <a aria-current="page" href="{% url 'updateEvent' organization.id event.id %}" ><button class="edit_button">{% trans "Edit" %}</button></a>
                        <a aria-current="page" href="{% url 'deleteEvent' organization.id event.id %}"><button class="edit_button">{% trans "Delete" %}</button></a> 
                    {% endif %}
                </div><br>
            {% endfor %}
        </div>
    {% else %}
        <p>{% trans "There are no events from this group." %}</p>
    {% endif %}
{% endblock %}

parent_resource_app/templates/parent_resource_app/organization_list.html
{% extends 'parent_resource_app/base_template.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Groups in Colorado" %}</h1><br>
    {% if organization_list %}
        <div class="d-grid">
            {% for group in organization_list %}
                <div class="a">
                    <h2 class="normal">{{ group.name }}</h2>
                    <p><strong>{% trans "About" %}: </strong>{{ group.about }}</p>
                    <a href="{{ group.get_absolute_url }}"><button class="edit_button">{% trans "View Details" %}</button></a>
                </div> <br>
            {% endfor %}
        </div>
    {% else %}
        <p>{% trans "There are no groups registered." %}</p>
    {% endif %}
{% endblock %}

parent_resource_app/templates/parent_resource_app/update_event.html
{% extends 'parent_resource_app/base_template.html' %}

{% block content%}
<form action="" method="POST">

    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="button" type="submit" name="Submit">

</form>
    

{%endblock%}

parent_resource_app/templates/parent_resource_app/update_group.html
{% extends 'parent_resource_app/base_template.html' %}

{% block content%}
<form action="" method="POST">

    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="button" type="submit" name="Submit">

</form>
    

{%endblock%}

parent_resource_app/templates/parent_resource_app/update_organization.html
{% extends 'parent_resource_app/base_template.html' %}

{% block content%}
<form action="" method="POST">

    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="button" type="submit" name="Submit">

</form>
    

{%endblock%}

parent_resource_app/templates/parent_resource_app/user.html
{% extends 'parent_resource_app/base_template.html' %}

{% block content%}

<h2>Welcome, {{ user.username }}! </h2><br>


<br><h3>My Profile</h3><br>
<div class="card">
    <p class="card-header">{{ user.organization.name }} </p>
    <div class="card-body">
        <p class='card-text'>Email: {{ user.email }}</p>
        <p class='card-text'>Phone: {{ user.organization.phone }}</p>
        <p class='card-text'>About: {{ user.organization.about }}</p>

    </div>
</div><br>
    
    
<a href="{% url 'updateOrganization' user.organization.id %}"><button class="button">Edit Group Profile</button></a>
<a href="{{ user.organization.get_absolute_url }}"><button class="button">View Public Page</button></a><br>
{% endblock %}